"use client"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { QueryClientProvider, QueryClient } from "react-query"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Laboratorio",
  description: "Generated by create next app",
}
export const queryClient = new QueryClient()
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <QueryClientProvider client={queryClient}>
      <html lang="es">
        <body className={inter.className}>{children}</body>
      </html>
    </QueryClientProvider>
  )
}
